### PR TITLE
Adding CGN scripts and dev/test configs

### PR DESCRIPTION
**Pull request by JeromeNi**
Modified setup_languages.sh and run.sh to add in CGN pre-processing; Added file lists for dev/test for CGN comp-o;

### CODE REVIEW

**Comment by pzelasko** [comment]
@JeromeNi you can use autopep8 to resolve the formatting issues (it has a flag for fixing errors in place) https://pypi.org/project/autopep8/

ESPnet uses this command in CI, you can use it to reproduce errors locally:
`autopep8 -r espnet test utils --global-config .pep8 --diff --max-line-length 120`

**Comment by JeromeNi** [comment]
@pzelasko I've checked using autopep8, but as the GitHub checks above, it only showed formatting issues of python code, right? In the PR I only modified several shell scripts, and uploaded three txt files related to splitting the CGN read speech section into train/dev/eval.

**Comment by pzelasko** [comment]
Hey Jerome, can you update your branch and resolve the conflicts? I fixed some bugs recently and added G2P conversion for multilingual IPA phone recognition. Thanks!

**Comment by JeromeNi** [comment]
I've merged the updated discophone branch with my branch locally. What flags should I use if I would like to turn off Global Phone data preparation, but turn on G2P conversion for multilingual IPA phone recognition, just to test the code is not breaking after the merge? Thanks!

**Comment by pzelasko** [comment]
Just set the globalphone related variables to be empty (gp_langs=)

niedz., 26 kwi 2020, 02:35 użytkownik JeromeNi <notifications@github.com>
napisał:

**Comment by JeromeNi** [comment]
Hello Piotr, I have now merged the changes, and have tested the first two stages. It seems to be working as I was able to see lexicon_ipa created for the train/dev/test set of CGN.

**Review by pzelasko — APPROVED** [review]

**Pull request merged**
